"""Generate and validate deterministic reproduction notebooks by production family."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from collections import Counter
from pathlib import Path
from typing import Any

import nbformat

from reproduce.build_parquet_reproduction_registry import (
    CATALOG_PATH,
    FAMILY_NOTEBOOKS,
    REGISTRY_PATH,
    ROOT,
    STATUSES,
    build_registry,
    command_for,
    family_for,
    producer_for,
)

OUTPUT_DIR = ROOT / "notebooks/reproduce"
README_PATH = OUTPUT_DIR / "README.md"
GENERATED_MARKER = "Generated by reproduce/generate_parquet_reproduction_notebooks.py; do not edit."


def _cell_id(index: int, source: str) -> str:
    return hashlib.sha256(f"{index}:{source}".encode()).hexdigest()[:12]


def _bullet(values: list[str], *, empty: str) -> str:
    return "\n".join(f"- `{value}`" for value in values) if values else f"- {empty}"


def _fields_table(fields: list[dict[str, Any]]) -> str:
    rows = ["| Column | Arrow dtype | Nullable |", "|---|---|---:|"]
    rows.extend(f"| `{f['name']}` | `{f['dtype']}` | `{str(f['nullable']).lower()}` |" for f in fields)
    return "\n".join(rows)


def _keys(record: dict[str, Any]) -> str:
    keys = record["keys"]
    return (
        f"- Source-contract key: {', '.join(f'`{v}`' for v in keys['source_contract']) or 'none declared'}\n"
        f"- Candidate/join key: {', '.join(f'`{v}`' for v in keys['candidate_join']) or 'none declared'}\n"
        f"- Linkage: {', '.join(f'`{v}`' for v in keys['linkage']) or 'none declared'}\n"
        f"- Uniqueness note: {keys['uniqueness']}"
    )


def _receipt(record: dict[str, Any]) -> str:
    receipt = record["migration_receipt"]
    sources = receipt.get("sources", [receipt.get("source")])
    source_lines = "\n".join(f"  - `{value}`" for value in sources if value)
    return (
        f"- Action: `{receipt['action']}`\n"
        f"- Preserved pre-migration source object(s):\n{source_lines}\n"
        f"- Destination generation: `{receipt['destination_generation']}`\n"
        f"- Destination CRC32C: `{receipt['destination_crc32c']}`\n"
        f"- Verified migration readback: `{receipt['verified']}`"
        + (f"\n- Destination SHA-256: `{receipt['destination_sha256']}`" if receipt.get("destination_sha256") else "")
    )


def family_records(registry: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for record in registry["records"]:
        grouped.setdefault(record["reproduce_notebook"], []).append(record)
    return {
        path: sorted(records, key=lambda row: (row["layer"], row["name"]))
        for path, records in sorted(grouped.items())
    }


def _output_table(records: list[dict[str, Any]]) -> str:
    rows = [
        "| Layer | Canonical output | Rows | Replay level | Catalog |",
        "|---|---|---:|---|---|",
    ]
    for record in records:
        dataset_id = f"{record['layer']}__{record['name']}"
        rows.append(
            f"| `{record['layer']}` | `{record['name']}` | {record['qc']['rows']:,} | "
            f"`{record['replay_level']}` | [catalog](../../{record['catalog_page']}) |"
        )
    return "\n".join(rows)


def _output_details(record: dict[str, Any]) -> str:
    dataset_id = f"{record['layer']}__{record['name']}"
    qc = record["qc"]
    command = record["full_worker_rebuild_command"]
    command_text = (
        f"```text\n{command}\n```\n\nThis exact argv is preserved as documentation only. It must run on an approved in-region worker, against worker-local verified inputs, with task-local staging and review before any canonical write."
        if command
        else "No verified exact full rebuild command is available. The lineage registry deliberately leaves this gap explicit rather than synthesizing an argv."
    )
    return f"""### Output `{dataset_id}`

- Canonical URI: `{record['canonical_uri']}`
- Catalog: [`{record['catalog_page']}`](../../{record['catalog_page']})
- Replay level: **`{record['replay_level']}`**
- Meaning: {record['meaning']}
- Does not mean: {record['non_meaning']}

**Native inputs and release.** {record['release']}

{_bullet(record['native_source'], empty='No selected native input is retained or resolvable from current evidence.')}

**Acquisition/preconditions.** {record['acquisition_and_preconditions']}

**Expected schema and identifiers.** Rows: **{qc['rows']:,}**; bytes: **{qc['bytes']:,}**; row groups: **{qc['row_groups']}**; schema hash (`{qc['schema_hash_version']}`): `{qc['schema_hash']}`; generation: `{qc['generation']}`; CRC32C: `{qc['crc32c_base64']}`.

{_fields_table(record['fields'])}

**Keys, mappings and joins.**

{_keys(record)}

{record['mappings_and_joins']}

**Cleaning, normalization, transformations and filters.** {record['transformations_and_filters']}

**Deduplication and assertion/evidence semantics.** {record['deduplication_and_evidence']}

**Quarantines, exclusions and missing data.** {record['quarantines_exclusions_missing']}

**Problems encountered and decisions.** {record['problems_and_decisions']}

Known gaps: {', '.join(f'`{value}`' for value in record['known_gaps']) or 'none declared'}.

**Producer / builder.** `{record['producer'] or 'not available as a current tracked builder'}`.

**Full worker rebuild command (inert; never executed here).**

{command_text}

**Migration receipt and QC.**

{_receipt(record)}

**Safe bounded replay.** {record['safe_bounded_replay']}

**Reproducibility limits.** {record['reproducibility_limits']}

**Linked code, tests, reports and historical notebooks.**

{_bullet(record['links'], empty='No additional tracked links.')}
"""


def build_family_notebook(records: list[dict[str, Any]]) -> nbformat.NotebookNode:
    if not records:
        raise ValueError("cannot build an empty family notebook")
    family_ids = {record["pipeline_family"] for record in records}
    notebook_paths = {record["reproduce_notebook"] for record in records}
    if len(family_ids) != 1 or len(notebook_paths) != 1:
        raise ValueError("family notebook records must have one family and one primary path")
    family_id = records[0]["pipeline_family"]
    family_label = records[0]["source_family_label"]
    intro = f"""# Reproduce {family_label}

{GENERATED_MARKER}

## Objective and meaning

Document the coherent `{family_id}` acquisition/build/mapping pipeline and safely verify all {len(records)} current canonical Parquets assigned to it.

Grouping justification: these outputs share a defensible source/transformation family context. Exact producer and command evidence remains per output and may be absent; layer alone is not used as a grouping rule, and differences remain explicit in each output contract.

## Canonical outputs owned by this notebook

{_output_table(records)}
"""
    guide = """## Native inputs, release, acquisition and environment

Shared acquisition context is stated once; release and retained input differences are restated under every owned output.

## Expected schema and identifiers

Each output section carries its exact catalog schema, row count, object generation and checksum.

## Keys, mappings and joins

Shared family mappings are applied only where stated; every output preserves its own key contract.

## Cleaning, normalization, transformations and filters

Transformation and filter differences are explicit per output below.

## Deduplication and assertion/evidence semantics

Canonical edges are deduplicated assertions; source-specific multiplicity and context remain evidence/features where applicable.

## Quarantines, exclusions and missing data

Every output contract states its known exclusions and unresolved provenance.

## Problems encountered and decisions

Known decisions and alternatives are reported conservatively; migration identity is not treated as proof of biological replayability.

## Producer / builder

The per-output contracts name an evidenced tracked producer or state that it is unavailable.

## Full worker rebuild command (inert text; never executed by this notebook)

Any command below is documentation only and remains approved-worker, staging and review gated.

## Migration receipt

Every output includes its generation-matched, verified migration receipt.

## QC, bounded replay and verification

The first code cell validates all embedded output contracts offline. The opt-in cell verifies one selected GCS object metadata record and Parquet footer, chosen with `JOUVENCE_OUTPUT_ID`; it never scans all family outputs.

## Reproducibility limits

Replay levels remain per output. No family-level label upgrades weaker members.

## Linked code, tests, reports and historical notebooks

Links are listed in each output contract.
"""
    details = "## Per-output reproduction contracts\n\n" + "\n\n".join(_output_details(record) for record in records)
    embedded = json.dumps(records, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    offline_code = f'''import hashlib
import json

RECORDS = json.loads(r\'''{embedded}\''')

def require(condition, message):
    if not condition:
        raise RuntimeError(message)

for RECORD in RECORDS:
    require(RECORD["canonical_uri"] == "gs://jouvencekb/main/" + ("embeddings" if RECORD["layer"] == "embedding" else RECORD["layer"]) + "/" + RECORD["name"] + ".parquet", "canonical URI/identity mismatch")
    require(RECORD["replay_level"] in {sorted(STATUSES)!r}, "unsupported replay level")
    require(RECORD["qc"]["rows"] >= 0, "negative expected row count")
    require(len(RECORD["qc"]["schema_hash"]) == 64, "invalid schema hash")
    require(RECORD["migration_receipt"]["verified"] is True, "migration receipt is not verified")
    require(bool(RECORD["fields"]), "empty expected schema")
summary = {{
    "pipeline_family": RECORDS[0]["pipeline_family"],
    "output_count": len(RECORDS),
    "identities": [record["layer"] + "__" + record["name"] for record in RECORDS],
}}
summary
'''
    live_code = '''import os

if os.environ.get("JOUVENCE_LIVE_GCS") != "1":
    live_result = {"status": "SKIPPED", "reason": "set JOUVENCE_LIVE_GCS=1 and caller-owned JOUVENCE_BILLING_PROJECT"}
else:
    import gcsfs
    import pyarrow.parquet as pq

    billing_project = os.environ.get("JOUVENCE_BILLING_PROJECT")
    if not billing_project:
        raise RuntimeError("JOUVENCE_BILLING_PROJECT is required for requester-pays live verification")
    fs = gcsfs.GCSFileSystem(project=billing_project, requester_pays=billing_project, version_aware=True)
    if not fs.version_aware:
        raise RuntimeError("version-aware GCS reads are required")
    selected_id = os.environ.get("JOUVENCE_OUTPUT_ID", RECORDS[0]["layer"] + "__" + RECORDS[0]["name"])
    selected = [record for record in RECORDS if record["layer"] + "__" + record["name"] == selected_id]
    if len(selected) != 1:
        raise RuntimeError("JOUVENCE_OUTPUT_ID must select exactly one output owned by this notebook")
    RECORD = selected[0]
    object_path = RECORD["canonical_uri"].removeprefix("gs://")
    if "#" in object_path:
        raise RuntimeError("canonical object key must not already contain a generation suffix")
    expected_generation = RECORD["qc"]["generation"]
    pinned_path = object_path + "#" + expected_generation
    info = fs.info(pinned_path)
    if str(info.get("generation", "")) != expected_generation:
        raise RuntimeError("generation-qualified object resolved a different generation")
    with fs.open(pinned_path, "rb") as handle:
        parquet = pq.ParquetFile(handle)
        live_fields = [
            {"name": field.name, "dtype": str(field.type), "nullable": bool(field.nullable)}
            for field in parquet.schema_arrow
        ]
        live_rows = parquet.metadata.num_rows
        live_row_groups = parquet.metadata.num_row_groups
    if live_rows != RECORD["qc"]["rows"]:
        raise RuntimeError("live footer row count differs from the frozen registry")
    if live_row_groups != RECORD["qc"]["row_groups"]:
        raise RuntimeError("live footer row-group count differs from the frozen registry")
    if live_fields != RECORD["fields"]:
        raise RuntimeError("live footer schema differs from the frozen registry")
    live_result = {"status": "PASS", "generation": str(info["generation"]), "rows": live_rows, "row_groups": live_row_groups}
live_result
'''
    notebook = nbformat.v4.new_notebook(
        cells=[
            nbformat.v4.new_markdown_cell(intro),
            nbformat.v4.new_markdown_cell(guide),
            nbformat.v4.new_markdown_cell(details),
            nbformat.v4.new_markdown_cell("## Offline bounded contract check\n\nThis cell uses only the embedded frozen lineage record."),
            nbformat.v4.new_code_cell(offline_code),
            nbformat.v4.new_markdown_cell("## Optional bounded live canonical footer check\n\nThis cell is skipped unless the caller explicitly opts in."),
            nbformat.v4.new_code_cell(live_code),
        ],
        metadata={
            "kernelspec": {"display_name": "Python 3 (ipykernel)", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
    )
    for index, cell in enumerate(notebook.cells):
        cell.id = _cell_id(index, cell.source)
        if cell.cell_type == "code":
            cell.execution_count = None
            cell.outputs = []
    return notebook


def build_readme(registry: dict[str, Any]) -> str:
    records = registry["records"]
    grouped = family_records(registry)
    counts = Counter(row["reproducibility_status"] for row in records)
    lines = [
        "# Canonical Parquet reproduction notebooks by production family",
        "",
        GENERATED_MARKER,
        "",
        f"This directory has {len(grouped)} generated, read-only-by-default production-family notebooks covering every current canonical Parquet in `gs://jouvencekb/main`. The exact 110-row denominator and identity spelling come from `docs/parquet-catalog/inventory.json`; each Parquet has exactly one primary notebook in `reproduce/parquet_reproduction_lineage.json`.",
        "",
        "These notebooks preserve and link the broader historical `reproduce/*.ipynb` source-family notebooks. A family notebook or byte-preserving migration receipt is not, by itself, proof that the original biological build is fully replayable.",
        "",
        "## Status summary",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    lines.extend(f"| `{status}` | {counts.get(status, 0)} |" for status in sorted(STATUSES))
    lines.extend([
        "",
        "## Safety and regeneration",
        "",
        "- Default execution is offline and validates only the embedded registry/receipt contract.",
        "- Live verification is opt-in with `JOUVENCE_LIVE_GCS=1` plus caller-owned `JOUVENCE_BILLING_PROJECT`; it reads metadata and a Parquet footer only.",
        "- Full rebuild commands are inert Markdown and remain worker-only/canonical-write-gated.",
        "- Regenerate: `uv run python reproduce/build_parquet_reproduction_registry.py && uv run python reproduce/generate_parquet_reproduction_notebooks.py`.",
        "- Check: `uv run python reproduce/generate_parquet_reproduction_notebooks.py --check`.",
        "",
        "## Grouping justification",
        "",
        "Families are based on a defensible source/transformation context, not superficial storage layer. Exact producer and command evidence remains per output and may be absent. Every notebook includes a visible owned-output table and a dedicated output contract for differences in schemas, keys, transformations, exclusions, QC, commands and gaps.",
        "",
        "| Pipeline family | Notebook | Parquets | Layers |",
        "|---|---|---:|---|",
    ])
    for path, family_rows in grouped.items():
        family = family_rows[0]["pipeline_family"]
        filename = Path(path).name
        layers = ", ".join(sorted({row["layer"] for row in family_rows}))
        lines.append(f"| `{family}` | [{filename}]({filename}) | {len(family_rows)} | {layers} |")
    lines.extend([
        "",
        "## Exact 110-output coverage matrix",
        "",
        "| Layer | Dataset | Pipeline family | Status | Rows | Primary notebook | Catalog |",
        "|---|---|---|---|---:|---|---|",
    ])
    for row in records:
        dataset_id = f"{row['layer']}__{row['name']}"
        filename = Path(row["reproduce_notebook"]).name
        lines.append(
            f"| `{row['layer']}` | `{row['name']}` | `{row['pipeline_family']}` | `{row['replay_level']}` | {row['qc']['rows']:,} | [{filename}]({filename}) | [catalog](../../{row['catalog_page']}) |"
        )
    return "\n".join(lines) + "\n"


def validate_registry(registry: dict[str, Any]) -> None:
    catalog = json.loads(CATALOG_PATH.read_text())
    expected = {(row["layer"], row["name"]) for row in catalog["datasets"]}
    actual = [(row["layer"], row["name"]) for row in registry["records"]]
    if len(actual) != len(set(actual)):
        raise SystemExit("duplicate lineage registry identities")
    if set(actual) != expected:
        raise SystemExit(f"registry/catalog mismatch: missing={sorted(expected - set(actual))}, stale={sorted(set(actual) - expected)}")
    if registry["record_count"] != len(actual) or len(actual) != catalog["dataset_count"]:
        raise SystemExit("registry count does not equal catalog denominator")
    grouped = family_records(registry)
    if not 1 <= len(grouped) <= 20:
        raise SystemExit(f"family notebook count outside 1..20: {len(grouped)}")
    for path, rows in grouped.items():
        if len({row["pipeline_family"] for row in rows}) != 1:
            raise SystemExit(f"multiple pipeline families share primary notebook: {path}")
    for row in registry["records"]:
        required_coverage = (
            row.get("canonical_uri"), row.get("layer"), row.get("name"),
            row.get("reproduce_notebook"), row.get("pipeline_family"),
        )
        if not all(required_coverage):
            raise SystemExit(f"incomplete primary coverage row: {row.get('layer')}__{row.get('name')}")
        expected_family = family_for(row["layer"], row["name"])
        if row["pipeline_family"] != expected_family or row["source_family"] != expected_family:
            raise SystemExit(f"authoritative pipeline family mismatch: {row['layer']}__{row['name']}")
        expected_notebook = f"notebooks/reproduce/{FAMILY_NOTEBOOKS[expected_family]}"
        if row["reproduce_notebook"] != expected_notebook:
            raise SystemExit(f"authoritative primary notebook mismatch: {row['layer']}__{row['name']}")
        dataset_id = f"{row['layer']}__{row['name']}"
        if row["producer"] != producer_for(dataset_id, expected_family):
            raise SystemExit(f"authoritative producer mismatch: {dataset_id}")
        if row["full_worker_rebuild_command"] != command_for(dataset_id, expected_family):
            raise SystemExit(f"authoritative rebuild command mismatch: {dataset_id}")
        if row["rebuild_command_evidenced"] is not (row["full_worker_rebuild_command"] is not None):
            raise SystemExit(f"rebuild command evidence flag mismatch: {dataset_id}")
        if row["producer"] != row["producer_builder"] or row["native_source"] != row["native_inputs"]:
            raise SystemExit(f"coverage lineage aliases disagree: {row['layer']}__{row['name']}")
        if row["replay_level"] != row["reproducibility_status"] or row["known_gaps"] != row["provenance_gaps"]:
            raise SystemExit(f"coverage replay aliases disagree: {row['layer']}__{row['name']}")
        if not row["reproduce_notebook"].startswith("notebooks/reproduce/") or not row["reproduce_notebook"].endswith(".ipynb"):
            raise SystemExit(f"invalid primary notebook path: {row['reproduce_notebook']}")
        if row["reproducibility_status"] not in STATUSES:
            raise SystemExit(f"invalid status: {row['reproducibility_status']}")
        if row["reproducibility_status"] == "fully-replayable":
            required = (row["native_inputs"], row["producer_builder"], row["full_worker_rebuild_command"], row["rebuild_command_evidenced"])
            if not all(required):
                raise SystemExit(f"overstated fully-replayable record: {row['layer']}__{row['name']}")
        for link in row["links"]:
            if link.startswith(("docs/", "reproduce/", "manage_db/", "tests/")) and not (ROOT / link).exists():
                raise SystemExit(f"missing tracked link for {row['layer']}__{row['name']}: {link}")
        receipt = row["migration_receipt"]
        if not receipt.get("verified") or receipt["destination_generation"] != row["qc"]["generation"]:
            raise SystemExit(f"inventory/migration receipt mismatch: {row['layer']}__{row['name']}")


def expected_files(registry: dict[str, Any]) -> dict[Path, str]:
    files = {README_PATH: build_readme(registry)}
    for relative_path, records in family_records(registry).items():
        files[ROOT / relative_path] = nbformat.writes(build_family_notebook(records))
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if registry or generated files are stale")
    args = parser.parse_args(argv)
    expected_registry = build_registry()
    if not REGISTRY_PATH.exists():
        if args.check:
            raise SystemExit(f"missing registry: {REGISTRY_PATH.relative_to(ROOT)}")
        REGISTRY_PATH.write_text(json.dumps(expected_registry, indent=2, sort_keys=True) + "\n")
    actual_registry = json.loads(REGISTRY_PATH.read_text())
    if actual_registry != expected_registry:
        if args.check:
            raise SystemExit("stale parquet reproduction lineage registry")
        REGISTRY_PATH.write_text(json.dumps(expected_registry, indent=2, sort_keys=True) + "\n")
        actual_registry = expected_registry
    validate_registry(actual_registry)
    files = expected_files(actual_registry)
    expected_notebooks = {path for path in files if path.suffix == ".ipynb"}
    existing_notebooks = set(OUTPUT_DIR.glob("*.ipynb")) if OUTPUT_DIR.exists() else set()
    if args.check:
        if existing_notebooks != expected_notebooks:
            raise SystemExit(f"generated notebook path mismatch: missing={sorted(str(p.relative_to(ROOT)) for p in expected_notebooks-existing_notebooks)}, stale={sorted(str(p.relative_to(ROOT)) for p in existing_notebooks-expected_notebooks)}")
        stale = [path.relative_to(ROOT).as_posix() for path, content in files.items() if not path.exists() or path.read_text() != content]
        if stale:
            raise SystemExit(f"stale generated reproduction files: {stale}")
        return 0
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path in existing_notebooks - expected_notebooks:
        path.unlink()
    for path, content in files.items():
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
