#!/usr/bin/env python3
"""Bounded audit for candidate inferred-edge templates over Jouvence KG v2.

This is intentionally read-only: it counts candidate links generated by relation-chain
patterns and anti-joins them against existing canonical observed edges. It does not
write inferred edges and does not promote anything to canonical KG tables.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import duckdb


DEFAULT_ROOT = Path('/Users/jkobject/mnt/gcs/jouvencekb/main')


def edge(root: Path, relation: str) -> str:
    path = root / 'edges' / f'{relation}.parquet'
    if not path.exists():
        raise FileNotFoundError(path)
    return str(path)


def scalar(con: duckdb.DuckDBPyConnection, sql: str) -> int:
    value = con.execute(sql).fetchone()[0]
    return int(value or 0)


def sample(con: duckdb.DuckDBPyConnection, sql: str, limit: int = 5) -> list[dict[str, Any]]:
    return con.execute(f"{sql}\nLIMIT {limit}").fetchdf().to_dict(orient='records')


def run(root: Path, mutation_limit: int, molecule_limit: int, sample_limit: int) -> dict[str, Any]:
    con = duckdb.connect(database=':memory:')
    con.execute('PRAGMA threads=4')

    paths = {
        'mutation_associated_gene': edge(root, 'mutation_associated_gene'),
        'mutation_associated_disease': edge(root, 'mutation_associated_disease'),
        'mutation_causes_protein_change': edge(root, 'mutation_causes_protein_change'),
        'disease_associated_gene': edge(root, 'disease_associated_gene'),
        'molecule_targets_gene': edge(root, 'molecule_targets_gene'),
        'molecule_treats_disease': edge(root, 'molecule_treats_disease'),
        'gene_associated_phenotype': edge(root, 'gene_associated_phenotype'),
        'disease_has_phenotype': edge(root, 'disease_has_phenotype'),
    }

    # Bounded mutation anchor set: deterministic first N mutations that have a disease edge.
    con.execute(f"""
        CREATE TEMP TABLE anchor_mutations AS
        SELECT DISTINCT x_id AS mutation_id
        FROM read_parquet('{paths['mutation_associated_disease']}')
        WHERE x_id IS NOT NULL AND y_id IS NOT NULL
        ORDER BY x_id
        LIMIT {mutation_limit}
    """)

    # Bounded molecule anchor set: deterministic first N molecules with target edges.
    con.execute(f"""
        CREATE TEMP TABLE anchor_molecules AS
        SELECT DISTINCT x_id AS molecule_id
        FROM read_parquet('{paths['molecule_targets_gene']}')
        WHERE x_id IS NOT NULL AND y_id IS NOT NULL
        ORDER BY x_id
        LIMIT {molecule_limit}
    """)

    results: dict[str, Any] = {
        'kg_root': str(root),
        'bounds': {
            'mutation_limit': mutation_limit,
            'molecule_limit': molecule_limit,
            'sample_limit': sample_limit,
        },
        'templates': {},
    }

    # Template A: mutation→gene + mutation→disease => candidate gene→disease.
    con.execute(f"""
        CREATE TEMP TABLE t_mutation_gene_disease AS
        SELECT DISTINCT
            mg.y_id AS candidate_x_id,
            md.y_id AS candidate_y_id,
            mg.x_id AS support_mutation_id
        FROM read_parquet('{paths['mutation_associated_gene']}') mg
        JOIN anchor_mutations am ON am.mutation_id = mg.x_id
        JOIN read_parquet('{paths['mutation_associated_disease']}') md ON md.x_id = mg.x_id
        WHERE mg.y_id IS NOT NULL AND md.y_id IS NOT NULL
    """)
    template_a_missing = """
        SELECT c.candidate_x_id AS gene_id, c.candidate_y_id AS disease_id, count(*) AS support_mutation_count
        FROM t_mutation_gene_disease c
        ANTI JOIN read_parquet('{disease_associated_gene}') obs
          ON obs.x_id = c.candidate_x_id AND obs.y_id = c.candidate_y_id
        GROUP BY 1, 2
        ORDER BY support_mutation_count DESC, gene_id, disease_id
    """.format(**paths)
    results['templates']['mutation_gene_plus_mutation_disease_to_gene_disease'] = {
        'chain': 'mutation_associated_gene(mutation,gene) + mutation_associated_disease(mutation,disease) => candidate disease_associated_gene(gene,disease)',
        'confidence_policy_hint': 'inferred_weak unless support mutation has direct containment/consequence evidence; do_not_infer for canonical promotion without independent gene-disease evidence',
        'raw_distinct_candidate_pairs': scalar(con, 'SELECT count(DISTINCT (candidate_x_id, candidate_y_id)) FROM t_mutation_gene_disease'),
        'missing_from_canonical_observed_pairs': scalar(con, f'SELECT count(*) FROM ({template_a_missing})'),
        'sample_missing': sample(con, template_a_missing, sample_limit),
    }

    # Template B: mutation→protein-change + mutation→disease => candidate protein→disease.
    con.execute(f"""
        CREATE TEMP TABLE t_mutation_protein_disease AS
        SELECT DISTINCT
            mp.y_id AS candidate_x_id,
            md.y_id AS candidate_y_id,
            mp.x_id AS support_mutation_id
        FROM read_parquet('{paths['mutation_causes_protein_change']}') mp
        JOIN anchor_mutations am ON am.mutation_id = mp.x_id
        JOIN read_parquet('{paths['mutation_associated_disease']}') md ON md.x_id = mp.x_id
        WHERE mp.y_id IS NOT NULL AND md.y_id IS NOT NULL
    """)
    template_b = """
        SELECT candidate_x_id AS protein_id, candidate_y_id AS disease_id, count(*) AS support_mutation_count
        FROM t_mutation_protein_disease
        GROUP BY 1, 2
        ORDER BY support_mutation_count DESC, protein_id, disease_id
    """
    results['templates']['mutation_protein_change_plus_mutation_disease_to_protein_disease'] = {
        'chain': 'mutation_causes_protein_change(mutation,protein) + mutation_associated_disease(mutation,disease) => candidate disease_associated_protein(protein,disease)',
        'confidence_policy_hint': 'inferred_weak; never replace protein-native disease evidence, and keep separate from canonical disease_associated_protein',
        'raw_distinct_candidate_pairs': scalar(con, 'SELECT count(DISTINCT (candidate_x_id, candidate_y_id)) FROM t_mutation_protein_disease'),
        'missing_from_canonical_observed_pairs': None,
        'missing_note': 'No canonical disease_associated_protein edge file exists in current v2/edges; relation is staged-only/deferred per relation coverage.',
        'sample_candidates': sample(con, template_b, sample_limit),
    }

    # Template C: molecule→gene target + gene→disease association => candidate molecule→disease.
    con.execute(f"""
        CREATE TEMP TABLE t_molecule_gene_disease AS
        SELECT DISTINCT
            mt.x_id AS candidate_x_id,
            dg.y_id AS candidate_y_id,
            mt.y_id AS support_gene_id
        FROM read_parquet('{paths['molecule_targets_gene']}') mt
        JOIN anchor_molecules am ON am.molecule_id = mt.x_id
        JOIN read_parquet('{paths['disease_associated_gene']}') dg ON dg.x_id = mt.y_id
        WHERE mt.x_id IS NOT NULL AND mt.y_id IS NOT NULL AND dg.y_id IS NOT NULL
    """)
    template_c_missing = """
        SELECT c.candidate_x_id AS molecule_id, c.candidate_y_id AS disease_id, count(*) AS support_gene_count
        FROM t_molecule_gene_disease c
        ANTI JOIN read_parquet('{molecule_treats_disease}') obs
          ON obs.x_id = c.candidate_x_id AND obs.y_id = c.candidate_y_id
        GROUP BY 1, 2
        ORDER BY support_gene_count DESC, molecule_id, disease_id
    """.format(**paths)
    results['templates']['molecule_target_gene_plus_gene_disease_to_molecule_disease'] = {
        'chain': 'molecule_targets_gene(molecule,gene) + disease_associated_gene(gene,disease) => candidate molecule_treats_disease(molecule,disease)',
        'confidence_policy_hint': 'inferred_weak / repurposing hypothesis only; contraindication/treatment direction and drug action sign require clinical or pharmacological evidence',
        'raw_distinct_candidate_pairs': scalar(con, 'SELECT count(DISTINCT (candidate_x_id, candidate_y_id)) FROM t_molecule_gene_disease'),
        'missing_from_canonical_observed_pairs': scalar(con, f'SELECT count(*) FROM ({template_c_missing})'),
        'sample_missing': sample(con, template_c_missing, sample_limit),
    }

    # Template D: gene→phenotype + disease→phenotype shared HPO => candidate gene→disease.
    con.execute(f"""
        CREATE TEMP TABLE t_gene_pheno_disease AS
        SELECT DISTINCT
            gp.x_id AS candidate_x_id,
            dh.x_id AS candidate_y_id,
            gp.y_id AS support_phenotype_id
        FROM read_parquet('{paths['gene_associated_phenotype']}') gp
        JOIN read_parquet('{paths['disease_has_phenotype']}') dh ON dh.y_id = gp.y_id
        WHERE gp.x_id IS NOT NULL AND gp.y_id IS NOT NULL AND dh.x_id IS NOT NULL
    """)
    template_d_missing = """
        SELECT c.candidate_x_id AS gene_id, c.candidate_y_id AS disease_id, count(*) AS shared_phenotype_count
        FROM t_gene_pheno_disease c
        ANTI JOIN read_parquet('{disease_associated_gene}') obs
          ON obs.x_id = c.candidate_x_id AND obs.y_id = c.candidate_y_id
        GROUP BY 1, 2
        ORDER BY shared_phenotype_count DESC, gene_id, disease_id
    """.format(**paths)
    results['templates']['shared_gene_and_disease_phenotype_to_gene_disease'] = {
        'chain': 'gene_associated_phenotype(gene,phenotype) + disease_has_phenotype(disease,phenotype) => candidate disease_associated_gene(gene,disease)',
        'confidence_policy_hint': 'do_not_infer by default; useful as retrieval/ranking feature only unless backed by independent gene-disease evidence',
        'raw_distinct_candidate_pairs': scalar(con, 'SELECT count(DISTINCT (candidate_x_id, candidate_y_id)) FROM t_gene_pheno_disease'),
        'missing_from_canonical_observed_pairs': scalar(con, f'SELECT count(*) FROM ({template_d_missing})'),
        'sample_missing': sample(con, template_d_missing, sample_limit),
    }

    return results


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--kg-root', type=Path, default=DEFAULT_ROOT)
    parser.add_argument('--mutation-limit', type=int, default=100_000)
    parser.add_argument('--molecule-limit', type=int, default=5_000)
    parser.add_argument('--sample-limit', type=int, default=5)
    parser.add_argument('--json', action='store_true', help='Emit only JSON')
    args = parser.parse_args()

    results = run(args.kg_root, args.mutation_limit, args.molecule_limit, args.sample_limit)
    if args.json:
        print(json.dumps(results, indent=2, sort_keys=True))
        return

    print('# Bounded inferred-edge candidate audit')
    print(json.dumps(results, indent=2, sort_keys=True))


if __name__ == '__main__':
    main()
