#!/usr/bin/env python3
"""Build and validate the public Jouvence Parquet catalog.

`refresh` performs bounded object listing and Parquet-footer reads only. It never
scans row payloads. `generate` is offline and renders Markdown from the checked-in
inventory. `check` fails for missing pages, stale generated content, duplicate
logical datasets, invalid schema hashes, or an inventory whose declared
coverage denominator is inconsistent.
"""

from __future__ import annotations

import argparse
import base64
import copy
import datetime as dt
import hashlib
import json
import re
from pathlib import Path
from typing import Any

CATALOG_DIR = Path("docs/parquet-catalog")
INVENTORY_PATH = CATALOG_DIR / "inventory.json"
GENERATED_MARKER = "<!-- generated by scripts/parquet_catalog.py; do not edit -->"
CANONICAL_ROOT = "gs://jouvencekb/main"
PROJECT = "jkobject-1549353370965"
FLAT_PREFIXES = (
    "nodes",
    "edges",
    "edges_inferred",
    "evidence",
    "evidence_inferred",
    "features",
    "embeddings",
)
SKIP_SUFFIXES = (".bak_20260618_ot",)
SCHEMA_HASH_VERSION = "arrow-fields-v1"

SPECIAL_DOCS = {
    "clinical_trials": "../inventory.json",
    "remap": "../inventory.json",
    "features": "../inventory.json",
    "evidence": "../../evidence_and_edge_schema_plan.md",
    "schema": "../../kg_schema_overview.md",
}


def _json_bytes(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def schema_hash(fields: list[dict[str, Any]]) -> str:
    payload = {"version": SCHEMA_HASH_VERSION, "fields": fields}
    return hashlib.sha256(_json_bytes(payload)).hexdigest()


def _clean_checksum(value: Any) -> str | None:
    if value in (None, ""):
        return None
    if isinstance(value, bytes):
        return base64.b64encode(value).decode()
    return str(value)


def _logical_groups(fs: Any) -> list[tuple[str, str, list[str]]]:
    groups: list[tuple[str, str, list[str]]] = []
    for prefix in FLAT_PREFIXES:
        layer = "embedding" if prefix == "embeddings" else prefix
        for path in sorted(fs.glob(f"jouvencekb/main/{prefix}/*.parquet")):
            if path.endswith(SKIP_SUFFIXES):
                continue
            stem = Path(path).stem
            groups.append((f"{layer}__{stem}", layer, [path]))
    return sorted(groups)


def _relation_semantics(name: str) -> dict[str, Any]:
    try:
        from manage_db.kg_schema import RELATION_BY_NAME

        spec = RELATION_BY_NAME.get(name)
    except Exception:
        spec = None
    if spec is None:
        return {}
    return {
        "x_type": spec.source.value,
        "y_type": spec.target.value,
        "kind": spec.kind.value,
        "direct": bool(spec.direct),
        "meaning": spec.notes or f"Canonical {name} assertion.",
        "non_meaning": "It is not evidence multiplicity: source-specific support belongs in the matching evidence table.",
    }


def _node_semantics(name: str) -> dict[str, Any]:
    try:
        from manage_db.kg_schema import NODE_TYPES, NodeType

        info = NODE_TYPES.get(NodeType(name))
    except Exception:
        info = None
    if info is None:
        return {}
    return {
        "node_type": name,
        "meaning": f"Canonical {name} registry keyed in the {info.primary_ontology} namespace (example `{info.example_id}`).",
        "non_meaning": "Presence is an identifier/registry assertion, not evidence for any biological relation.",
        "lamin": info.bionty_registry or f"custom lnschema_txgnn registry for {name}",
    }


def _generic_semantics(layer: str, name: str, uri: str) -> dict[str, Any]:
    if layer == "nodes":
        return _node_semantics(name)
    if layer in {"edges", "evidence"}:
        rel = _relation_semantics(name)
        if layer == "evidence":
            rel.update(
                meaning=f"Source-level support records for the canonical `{name}` assertion.",
                non_meaning="Rows are not additional graph edges and evidence row count is not edge count or independent-study count.",
            )
        return rel
    if layer == "embedding":
        node_type = name.split("_text_", 1)[0] if "_text_" in name else name.split("_", 1)[0]
        return {
            "node_type": node_type,
            "meaning": f"Accepted learned vector table for canonical `{node_type}` nodes.",
            "non_meaning": "Vector similarity is not functional equivalence, causality, or therapeutic evidence.",
        }
    if "textual_summary" in name:
        node_type = name.removesuffix("_textual_summary")
        return {
            "node_type": node_type,
            "meaning": f"Source-backed text payloads for `{node_type}` nodes, suitable for retrieval or text feature construction.",
            "non_meaning": "Text is not a curated label, causal claim, or complete coverage of the node table.",
        }
    if name == "protein_sequence":
        return {"node_type": "protein", "meaning": "Ensembl human protein sequences keyed to canonical protein nodes.", "non_meaning": "Rows are sequences, not protein-function labels or one row for every protein node."}
    if name == "transcript_sequence":
        return {"node_type": "transcript", "meaning": "Ensembl human transcript cDNA sequences keyed to canonical transcript nodes.", "non_meaning": "Rows are cDNA payloads, not gene-level sequence or protein sequence."}
    if name == "molecule_fingerprint":
        return {"node_type": "molecule", "meaning": "Deterministic RDKit Morgan sparse binary fingerprints for parseable molecule SMILES.", "non_meaning": "This is a deterministic cheminformatics baseline, not a learned molecular embedding."}
    if "clinical_trials_gov" in uri:
        return {"meaning": "ClinicalTrials.gov sidecar keyed by NCT ID or a canonical treatment-edge support key.", "non_meaning": "It is not graph topology, a clinical-trial node layer, participant-level data, or a treatment label.", "leakage": "Trial status, outcomes, interventions and text can reveal held-out treatment evidence; split or mask for treatment prediction."}
    if "remap_crm" in uri:
        return {"meaning": "ReMap 2022 compact CRM aggregate support/QA features.", "non_meaning": "Not graph topology, not observed binding, and not canonical `tf_binds_enhancer` edge/evidence.", "leakage": "Exclude from default topology and supervised regulatory labels unless a reviewed split policy permits it."}
    if layer == "proof":
        return {"meaning": "Row-level validation proof bound to a promoted canonical relation.", "non_meaning": "Proof rows are audit material, not graph topology or an independent biological assertion."}
    return {"meaning": f"Canonical public `{name}` {layer} table.", "non_meaning": "Interpret only according to its columns and linked provenance; it is not an implicit graph relation."}


def _keys(layer: str, fields: list[dict[str, Any]], name: str) -> dict[str, Any]:
    columns = {f["name"] for f in fields}
    unvalidated = "uniqueness unvalidated by footer-only catalog collection"
    if layer == "nodes" and "id" in columns:
        return {
            "source_contract": ["id"],
            "candidate_join": [],
            "linkage": [],
            "uniqueness": unvalidated,
        }
    if layer == "edges":
        return {
            "source_contract": [c for c in ("relation", "x_id", "y_id") if c in columns],
            "candidate_join": [],
            "linkage": ["x_id -> nodes/<x_type>.id", "y_id -> nodes/<y_type>.id"],
            "uniqueness": unvalidated,
        }
    if layer == "evidence":
        edge_links = []
        if {"relation", "x_id", "y_id"} <= columns:
            edge_links.append("(relation, x_id, y_id) -> matching edge assertion")
        if "edge_key" in columns:
            edge_links.append("edge_key -> matching edge assertion")
        candidates = ["source_record_id"] if "source_record_id" in columns else []
        return {
            "source_contract": [],
            "candidate_join": candidates,
            "linkage": edge_links,
            "uniqueness": unvalidated,
        }
    candidates = [c for c in ("feature_key", "embedding_key", "node_id", "nct_id", "edge_key", "support_entity_id") if c in columns]
    return {
        "source_contract": [],
        "candidate_join": candidates,
        "linkage": [c for c in ("node_id", "edge_key", "nct_id", "enhancer_id", "tf_gene_id") if c in columns],
        "uniqueness": unvalidated,
    }


def _status(layer: str, uri: str) -> str:
    if "hashing_vectorizer/scaffold_v1" in uri:
        return "canonical promoted scaffold"
    if "hashing_vectorizer/full_staged_fallback_v1" in uri:
        return "canonical promoted fallback sidecar"
    if "remap_crm_tf_enhancer_support_full" in uri:
        return "canonical promoted support-only sidecar"
    return "canonical present"


def refresh(release_contract: Path | None, *, write: bool = True) -> dict[str, Any]:
    import gcsfs
    import pyarrow.parquet as pq

    fs = gcsfs.GCSFileSystem(project=PROJECT, requester_pays=PROJECT)
    datasets: list[dict[str, Any]] = []
    for dataset_id, layer, paths in _logical_groups(fs):
        fields: list[dict[str, Any]] | None = None
        objects = []
        rows = row_groups = total_bytes = 0
        for path in sorted(paths):
            info = fs.info(path)
            with fs.open(path, "rb") as handle:
                parquet = pq.ParquetFile(handle)
                current_fields = [
                    {"name": field.name, "dtype": str(field.type), "nullable": bool(field.nullable)}
                    for field in parquet.schema_arrow
                ]
                if fields is None:
                    fields = current_fields
                elif fields != current_fields:
                    raise SystemExit(f"schema mismatch inside logical dataset {dataset_id}: {path}")
                object_rows = int(parquet.metadata.num_rows)
                object_row_groups = int(parquet.metadata.num_row_groups)
            size = int(info.get("size", 0))
            rows += object_rows
            row_groups += object_row_groups
            total_bytes += size
            objects.append(
                {
                    "uri": "gs://" + path,
                    "rows": object_rows,
                    "bytes": size,
                    "generation": str(info.get("generation", "")) or None,
                    "updated": str(info.get("updated", "")) or None,
                    "crc32c_base64": _clean_checksum(info.get("crc32c")),
                    "md5_base64": _clean_checksum(info.get("md5Hash") or info.get("md5")),
                }
            )
        assert fields is not None
        name = dataset_id.split("__", 1)[-1]
        uri = objects[0]["uri"] if len(objects) == 1 else _uri_pattern(objects)
        semantics = _generic_semantics(layer, name, uri)
        datasets.append(
            {
                "id": dataset_id,
                "layer": layer,
                "name": name,
                "status": _status(layer, uri),
                "as_of": max((o["updated"] or "" for o in objects), default="")[:10] or None,
                "uri": uri,
                "rows": rows,
                "bytes": total_bytes,
                "row_groups": row_groups,
                "objects": objects,
                "schema_hash": schema_hash(fields),
                "schema_hash_version": SCHEMA_HASH_VERSION,
                "fields": fields,
                "keys": _keys(layer, fields, name),
                "semantics": semantics,
                "source_release_license_provenance": _provenance(layer, name, uri),
                "links": _links(layer, uri),
            }
        )
    if release_contract:
        datasets.extend(_planned_embeddings(release_contract))
    datasets.sort(key=lambda item: (item["layer"], item["id"]))
    inventory = {
        "schema_version": "jouvence.parquet_catalog.v1",
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "canonical_root": CANONICAL_ROOT,
        "collection_method": "bounded GCS object listing plus Parquet footer/schema reads; no row-payload scan",
        "schema_hash_version": SCHEMA_HASH_VERSION,
        "dataset_count": len(datasets),
        "documented_count": len(datasets),
        "undocumented_count": 0,
        "datasets": datasets,
    }
    if write:
        CATALOG_DIR.mkdir(parents=True, exist_ok=True)
        INVENTORY_PATH.write_text(json.dumps(inventory, indent=2, sort_keys=True) + "\n")
    return inventory


def _uri_pattern(objects: list[dict[str, Any]]) -> str:
    uris = [o["uri"] for o in objects]
    parents = {uri.rpartition("/")[0] for uri in uris}
    if len(parents) == 1:
        return sorted(parents)[0] + "/part-*.parquet"
    return " | ".join(uris)


def _provenance(layer: str, name: str, uri: str) -> dict[str, str]:
    if "clinical_trials_gov" in uri:
        return {"source": "ClinicalTrials.gov API v2 with OpenTargets treatment links where applicable", "release": "See row-level/source manifest metadata", "license": "See canonical source/license report; downstream redistribution remains subject to source review", "provenance": SPECIAL_DOCS["clinical_trials"]}
    if "remap_crm" in uri:
        return {"source": "ReMap", "release": "2022; GRCh38/hg38", "license": "See canonical manifest/source terms", "provenance": SPECIAL_DOCS["remap"]}
    if layer == "features":
        return {"source": "Source is recorded in row-level provenance columns", "release": "See row-level `source_release` and object generation", "license": "See row-level `license`; obligations vary by source", "provenance": SPECIAL_DOCS["features"]}
    if layer == "evidence":
        return {"source": "Source-specific support rows", "release": "See row-level `release`/`source_dataset`", "license": "See row-level `license`; absence must not be interpreted as unrestricted use", "provenance": SPECIAL_DOCS["evidence"]}
    return {"source": "See table `source` columns and linked KG schema", "release": "Object generation/update date in this catalog; biological source release may be row-level", "license": "Not derivable from Parquet metadata alone; consult source provenance before redistribution", "provenance": SPECIAL_DOCS["schema"]}


def _links(layer: str, uri: str) -> dict[str, str]:
    links = {"catalog_manifest": "../inventory.json", "schema_doc": SPECIAL_DOCS["schema"]}
    if layer == "evidence":
        links["evidence_doc"] = SPECIAL_DOCS["evidence"]
    return links


def _planned_embeddings(path: Path) -> list[dict[str, Any]]:
    contract = json.loads(path.read_text())
    common = contract["common_release_schema"]
    dtype_map = common["release_physical_types"]
    fields = [
        {
            "name": name,
            "dtype": dtype_map.get(name, "not specified by accepted release contract"),
            "nullable": False if name == "window_count" else None,
        }
        for name in common["required_columns"]
    ]
    leaves = contract["release_topology"]["included_leaf_targets"]
    by_dataset = {item["dataset_id"]: item for item in contract["datasets"]}
    result = []
    for leaf in leaves:
        source = by_dataset[leaf["dataset_id"]]
        logical = source["logical_dataset"]
        node_type = leaf["node_type"]
        source_features = source.get("source_features", [])
        if source_features:
            rows = next(item["rows"] for item in source_features if item["node_type"] == node_type)
        else:
            rows = logical["rows"]
        leaf_fields = copy.deepcopy(fields)
        dim = logical["embedding_dim"]
        for field in leaf_fields:
            if field["name"] == "embedding":
                field["dtype"] = f"fixed_size_list<float32>[{dim}]"
            elif field["name"] == "embedding_dim":
                field["dtype"] = f"int32 constant {dim}"
        dataset_id = "planned_embedding__" + re.sub(r"[^a-zA-Z0-9]+", "__", leaf["root"].split("features/embeddings/", 1)[1]).strip("_")
        result.append(
            {
                "id": dataset_id,
                "layer": "embedding",
                "name": f"{leaf['dataset_id']}__{node_type}",
                "status": source["status"] + "; not published",
                "as_of": contract["created_at_paris"][:10],
                "uri": leaf["root"] + "part-*.parquet",
                "rows": int(rows),
                "bytes": None,
                "row_groups": None,
                "objects": [],
                "schema_hash": schema_hash(leaf_fields),
                "schema_hash_version": SCHEMA_HASH_VERSION,
                "fields": leaf_fields,
                "keys": {
                    "source_contract": ["embedding_key (planned release contract)"],
                    "candidate_join": [],
                    "linkage": ["node_id -> nodes/<node_type>.id", "source_feature_key -> source feature table"],
                    "uniqueness": "unavailable and unvalidated until publication",
                },
                "semantics": {"node_type": node_type, "meaning": f"Planned source-backed `{logical['modality']}` embeddings for `{node_type}` nodes using `{logical['model']}`.", "non_meaning": "Not published and not a learned fallback for nodes without source features; status is blocked until the release contract blockers are resolved.", "leakage": "Split by canonical node/edge task before fitting or evaluating; source text/clinical payloads may encode target evidence."},
                "source_release_license_provenance": {"source": "Source feature URI(s) are bound in the accepted release inventory", "release": logical["embedding_version"], "license": "Blocked: effective public model/output license is unresolved", "provenance": "../embedding-release-inventory.json"},
                "links": {"catalog_manifest": "../inventory.json", "release_inventory": "../embedding-release-inventory.json", "planned_schema": leaf["schema_uri"], "planned_checksums": leaf["checksums_uri"], "planned_readme": leaf["readme_uri"]},
                "planned_data_objects": leaf["planned_data_objects"],
                "blockers": source["blockers"],
            }
        )
    return result


def _read_inventory() -> dict[str, Any]:
    return json.loads(INVENTORY_PATH.read_text())


def _md_escape(text: Any) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _page(dataset: dict[str, Any]) -> str:
    sem = dataset["semantics"]
    prov = dataset["source_release_license_provenance"]
    fields = dataset["fields"]
    uri = dataset["uri"]
    access_uri = uri.replace("summary_chr{1..22,X,Y}.parquet", "summary_chr*.parquet")
    gcsfs_pattern = access_uri.removeprefix("gs://")
    sample_column = fields[0]["name"] if fields else "*"
    sql_sample_column = '"' + sample_column.replace('"', '""') + '"'
    local_dir = f"./parquet-catalog-data/{dataset['id']}"
    if len(dataset["objects"]) == 1:
        local_pattern = f"{local_dir}/{Path(dataset['objects'][0]['uri']).name}"
    elif "summary_chr" in access_uri:
        local_pattern = f"{local_dir}/summary_chr*.parquet"
    else:
        local_pattern = f"{local_dir}/part-*.parquet"
    date = dataset.get("as_of") or "not recorded"
    keys = dataset["keys"]
    lines = [
        GENERATED_MARKER,
        f"# `{dataset['id']}`",
        "",
        f"- Layer: `{dataset['layer']}`",
        f"- Status: **{dataset['status']}**",
        f"- As of: `{date}`",
        f"- Canonical URI/pattern: `{uri}`",
        f"- Logical rows: **{dataset['rows']:,}**",
        f"- Physical objects: **{len(dataset['objects']) or dataset.get('planned_data_objects', 0)}**",
        f"- Bytes: **{dataset['bytes']:,}**" if dataset.get("bytes") is not None else "- Bytes: **not measured (not published)**",
        f"- Schema hash (`{dataset['schema_hash_version']}`): `{dataset['schema_hash']}`",
        "",
        "## Meaning",
        "",
        sem.get("meaning", "Not recorded."),
        "",
        "**Does not mean:** " + sem.get("non_meaning", "No broader semantics are implied."),
        "",
        "## Keys and graph contract",
        "",
        f"- Source-contract key fields: `{', '.join(keys['source_contract']) or 'none declared'}`",
        f"- Candidate/join key fields: `{', '.join(keys['candidate_join']) or 'none declared'}`",
        f"- Uniqueness validation: **{keys['uniqueness']}**",
        f"- Foreign keys/linkage: `{'; '.join(keys['linkage']) or 'none declared'}`",
    ]
    for key in ("node_type", "x_type", "y_type", "kind", "direct"):
        if key in sem:
            lines.append(f"- {key}: `{sem[key]}`")
    lines.extend(["", "## Columns", "", "| Column | Arrow dtype | Nullable |", "|---|---|---:|"])
    lines.extend(
        f"| `{_md_escape(f['name'])}` | `{_md_escape(f['dtype'])}` | `{'unknown (not published)' if f['nullable'] is None else str(f['nullable']).lower()}` |"
        for f in fields
    )
    lines.extend([
        "",
        "## Source, release, license and provenance",
        "",
        f"- Source: {prov['source']}",
        f"- Release: {prov['release']}",
        f"- License: {prov['license']}",
        f"- Provenance: [{prov['provenance']}]({prov['provenance']})" if not prov["provenance"].startswith("gs://") else f"- Provenance: `{prov['provenance']}`",
        "",
        "## Layout and checksums",
        "",
        (
            f"The logical dataset is represented by `{len(dataset['objects'])}` physical Parquet object(s). Physical shards are packaging, not separate datasets."
            if dataset["objects"]
            else f"The release contract plans `{dataset.get('planned_data_objects', 0)}` physical Parquet object(s), but none are published or accessible."
        ),
        "",
    ])
    if dataset["objects"]:
        lines.extend(["| Object | Rows | Bytes | Generation | CRC32C | MD5 |", "|---|---:|---:|---|---|---|"])
        for obj in dataset["objects"]:
            lines.append(f"| `{obj['uri']}` | {obj['rows']:,} | {obj['bytes']:,} | `{obj.get('generation') or 'n/a'}` | `{obj.get('crc32c_base64') or 'n/a'}` | `{obj.get('md5_base64') or 'n/a'}` |")
    for label, target in dataset.get("links", {}).items():
        lines.append(f"- {label}: `{target}`" if target.startswith("gs://") else f"- {label}: [{target}]({target})")
    if dataset["objects"]:
        lines.extend([
            "",
            "## Read examples",
            "",
            "Requester-pays prerequisite (once public IAM permits it):",
            "",
            "```bash",
            "export BILLING_PROJECT='<your-gcp-billing-project>'",
            f"LOCAL_DIR='{local_dir}'",
            "rm -rf -- \"$LOCAL_DIR\"",
            "mkdir -p \"$LOCAL_DIR\"",
            f"gcloud storage cp --billing-project=\"$BILLING_PROJECT\" '{access_uri}' \"$LOCAL_DIR/\"",
            "```",
            "",
            "PyArrow (GCS credentials/application-default credentials must carry the billing project):",
            "",
            "```python",
            "import os",
            "import gcsfs",
            "import pyarrow.dataset as ds",
            "billing_project = os.environ['BILLING_PROJECT']",
            "fs = gcsfs.GCSFileSystem(project=billing_project, requester_pays=billing_project)",
            f"paths = sorted(fs.glob('{gcsfs_pattern}'))",
            "dataset = ds.dataset(paths, filesystem=fs, format='parquet')",
            f"print(dataset.head(5, columns=['{sample_column}']))",
            "```",
            "",
            "DuckDB:",
            "",
            "```sql",
            "-- Run after the requester-pays `gcloud storage cp` command above.",
            f"SELECT {sql_sample_column} FROM read_parquet('{local_pattern}') ORDER BY {sql_sample_column} NULLS LAST LIMIT 5;",
            "```",
        ])
    else:
        lines.extend([
            "",
            "## Post-publication access template (non-executable)",
            "",
            "Current access is unavailable: this planned dataset has no published objects. The template below is intentionally non-executable and must be replaced with released object names after publication.",
            "",
            "```text",
            "NON-EXECUTABLE POST-PUBLICATION TEMPLATE",
            f"REMOTE_OBJECT = <published object under {uri}>",
            f"LOCAL_OBJECT = {local_dir}/<published-shard>.parquet",
            "QUERY = <select a documented column from LOCAL_OBJECT after publication>",
            "```",
        ])
    lines.extend([
        "",
        "## LaminDB / PyG linkage",
        "",
        _linkage(dataset),
        "",
        "## Caveats and leakage",
        "",
        sem.get("leakage", _default_leakage(dataset)),
    ])
    if dataset.get("blockers"):
        lines.extend(["", "Publication blockers:"] + [f"- {item}" for item in dataset["blockers"]])
    return "\n".join(lines) + "\n"


def _linkage(dataset: dict[str, Any]) -> str:
    layer = dataset["layer"]
    sem = dataset["semantics"]
    if layer == "nodes":
        return f"`id` links to {sem.get('lamin', 'the matching LaminDB/bionty registry')}. PyG uses this table to define the node store; it does not create adjacency."
    if layer == "edges":
        return "`x_id` and `y_id` resolve against canonical node tables. Eligible biological relations become PyG edge stores; metadata-only relations must remain excluded from default training exports."
    if layer == "evidence":
        return "Evidence links to the collapsed edge by `(relation, x_id, y_id)` / `edge_key`. It is side metadata and is not expanded into duplicate PyG edges."
    return "This is a sidecar. Join through the declared node/edge/NCT keys; it is not topology unless a separate reviewed exporter explicitly consumes it."


def _default_leakage(dataset: dict[str, Any]) -> str:
    if dataset["layer"] in {"edges", "evidence"}:
        return "Construct train/validation/test splits before exposing relation or evidence fields. Evidence counts, predicates, scores and source text can leak held-out edge labels."
    if dataset["layer"] == "nodes":
        return "Identifiers and ontology hierarchy may encode target structure. Keep split policy explicit and do not infer missing biological assertions from registry membership."
    return "Feature coverage is partial and source-dependent. Fit preprocessing only on the training partition and mask features that directly encode the evaluation target."


def _render_catalog(inventory: dict[str, Any]) -> tuple[dict[str, str], str]:
    pages: dict[str, str] = {}
    for dataset in inventory["datasets"]:
        filename = dataset["id"] + ".md"
        pages[filename] = _page(dataset)
    by_layer: dict[str, list[dict[str, Any]]] = {}
    for dataset in inventory["datasets"]:
        by_layer.setdefault(dataset["layer"], []).append(dataset)
    lines = [
        GENERATED_MARKER,
        "# Jouvence public Parquet catalog",
        "",
        f"This catalog documents **{inventory['documented_count']} / {inventory['dataset_count']}** logical Parquet datasets; **{inventory['undocumented_count']} undocumented**.",
        "",
        f"Facts were frozen at `{inventory['generated_at']}` using {inventory['collection_method']}. One page represents one logical dataset, never one physical shard.",
        "",
        "Access requires a consumer billing project when requester-pays is enabled:",
        "",
        "```bash",
        "export BILLING_PROJECT='<your-gcp-billing-project>'",
        "gcloud storage ls --billing-project=\"$BILLING_PROJECT\" gs://jouvencekb/main/",
        "```",
        "",
        "Schema/count facts come from `inventory.json`; `uv run python scripts/parquet_catalog.py check` validates the frozen catalog, while `uv run python scripts/parquet_catalog.py check --live` also performs bounded GCS listings/footer reads and fails on undocumented logical datasets, row drift, or live schema drift.",
        "",
    ]
    for layer in sorted(by_layer):
        items = sorted(by_layer[layer], key=lambda item: item["id"])
        lines.extend([f"## {layer} ({len(items)})", "", "| Dataset | Rows | Status | URI/pattern |", "|---|---:|---|---|"])
        for item in items:
            lines.append(f"| [`{item['id']}`](datasets/{item['id']}.md) | {item['rows']:,} | {item['status']} | `{item['uri']}` |")
        lines.append("")
    return pages, "\n".join(lines)


def generate() -> dict[str, int]:
    inventory = _read_inventory()
    pages_dir = CATALOG_DIR / "datasets"
    pages_dir.mkdir(parents=True, exist_ok=True)
    pages, index = _render_catalog(inventory)
    for filename, content in pages.items():
        (pages_dir / filename).write_text(content)
    for path in pages_dir.glob("*.md"):
        if path.name not in pages:
            path.unlink()
    (CATALOG_DIR / "index.md").write_text(index)
    return {"documented": len(pages), "undocumented": 0}


def check(*, live: bool = False) -> dict[str, int]:
    inventory = _read_inventory()
    errors = []
    datasets = inventory.get("datasets", [])
    ids = [item["id"] for item in datasets]
    if len(ids) != len(set(ids)):
        errors.append("duplicate logical dataset ids")
    if inventory.get("dataset_count") != len(datasets):
        errors.append("dataset_count does not equal inventory datasets length")
    if inventory.get("documented_count") != len(datasets) or inventory.get("undocumented_count") != 0:
        errors.append("coverage denominator must declare every inventory dataset documented")
    for item in datasets:
        expected_hash = schema_hash(item["fields"])
        if item.get("schema_hash") != expected_hash:
            errors.append(f"stale schema hash: {item['id']}")
    if live:
        live_inventory = refresh(None, write=False)
        frozen_by_id = {item["id"]: item for item in datasets}
        live_by_id = {item["id"]: item for item in live_inventory["datasets"]}
        missing_live_docs = sorted(set(live_by_id) - set(frozen_by_id))
        removed_live = sorted(set(frozen_by_id) - set(live_by_id))
        if missing_live_docs:
            errors.append("live undocumented logical datasets: " + ", ".join(missing_live_docs))
        if removed_live:
            errors.append("catalog datasets absent from live inventory: " + ", ".join(removed_live))
        for dataset_id in sorted(set(frozen_by_id) & set(live_by_id)):
            frozen = frozen_by_id[dataset_id]
            observed = live_by_id[dataset_id]
            if frozen["schema_hash"] != observed["schema_hash"]:
                errors.append(f"live schema drift: {dataset_id}")
            if frozen["rows"] != observed["rows"]:
                errors.append(f"live row-count drift: {dataset_id}")
    rendered_pages, rendered_index = _render_catalog(inventory)
    expected_pages = set(rendered_pages)
    actual_pages = {path.name for path in (CATALOG_DIR / "datasets").glob("*.md")}
    missing = expected_pages - actual_pages
    extra = actual_pages - expected_pages
    if missing:
        errors.append("missing pages: " + ", ".join(sorted(missing)))
    if extra:
        errors.append("undocumented pages: " + ", ".join(sorted(extra)))
    for filename, expected_content in rendered_pages.items():
        path = CATALOG_DIR / "datasets" / filename
        if path.exists() and path.read_text() != expected_content:
            errors.append(f"stale generated page: {path.stem}")
    index_path = CATALOG_DIR / "index.md"
    if not index_path.exists() or index_path.read_text() != rendered_index:
        errors.append("stale generated index")
    forbidden = re.compile(r"/Users/|/home/ubuntu|\.omoc/")
    for path in [CATALOG_DIR / "index.md", *sorted((CATALOG_DIR / "datasets").glob("*.md"))]:
        if path.exists() and forbidden.search(path.read_text()):
            errors.append(f"local/legacy path leaked into {path}")
    if errors:
        raise SystemExit("catalog check failed:\n- " + "\n- ".join(errors))
    generated = {"documented": len(rendered_pages), "undocumented": 0}
    print(json.dumps({**generated, "dataset_count": len(datasets)}, sort_keys=True))
    return generated


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    refresh_parser = sub.add_parser("refresh")
    refresh_parser.add_argument("--release-contract", type=Path)
    sub.add_parser("generate")
    check_parser = sub.add_parser("check")
    check_parser.add_argument("--live", action="store_true", help="compare frozen inventory with bounded live GCS footer reads")
    args = parser.parse_args()
    if args.command == "refresh":
        data = refresh(args.release_contract)
        print(json.dumps({"dataset_count": data["dataset_count"]}, sort_keys=True))
    elif args.command == "generate":
        print(json.dumps(generate(), sort_keys=True))
    else:
        check(live=args.live)


if __name__ == "__main__":
    main()
